version: '3.4'

services:
   catalogdb:
        image: mongo
        container_name: catalogdb
        restart: always
        volumes:
            - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - "27017:27017"

   catalog.api:
        image: fring02/microservicesapp:catalogapi
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
        depends_on:
          - catalogdb
        volumes:
          - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
          - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
          - "8000:80"

   basketdb:
        image: redis
        container_name: basketdb
        restart: always
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - ./redis/volume/:/data
        ports:
            - "6379:6379"

   basket.api:
        image: fring02/microservicesapp:basketapi
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "ConnectionStrings:Redis=basketdb:6379"
        depends_on:
            - basketdb
        ports:
            - "5001:80"
        volumes:
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
